name: 🔨 Build Test
on:
  push:
  pull_request:
  workflow_dispatch:


jobs:  
  build:
    name: Test Builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Check out code
        uses: actions/checkout@v2

      - name: Test
        run: go test ./...
        working-directory: .

      - name: Build
        run: go build ./...
        working-directory: .